const fs = require('fs');
const code = fs.readFileSync('src/components/CobrancasPage.tsx', 'utf8');
const lines = code.split('\n');
lines.splice(697, 34,
'          <p className="text-xs text-slate-400 font-semibold">Consulte, cobre no WhatsApp via IA, e controle inadimplência da sua base direta do Vale do Taquari</p>',
'        </div>',
'        <div className="flex gap-2">',
'          {onRefreshData && (',
'            <button',
'              onClick={onRefreshData}',
'              className="p-2.5 card-modern border border-slate-200 hover:border-slate-300 text-slate-500 hover:text-sky-600 rounded-xl transition cursor-pointer"',
'              title="Recarregar Clientes e Contas da Planilha"',
'            >',
'              <Clock className="w-4 h-4" />',
'            </button>',
'          )}',
'          <button',
'            onClick={() => setViewMode("dashboard")}',
'            className="flex items-center gap-2 px-4 py-2.5 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-bold shadow-md shadow-slate-900/20 cursor-pointer transition active:scale-95 shrink-0"',
'          >',
'            <Bot className="w-4 h-4 text-emerald-400" />',
'            <span>Dashboard Gerencial</span>',
'          </button>',
'          <button',
'            onClick={() => setIsBulkImportOpen(true)}',
'            className="flex items-center gap-2 px-4 py-2.5 card-modern hover:bg-slate-50 border border-slate-200 text-slate-700 hover:text-rose-700 rounded-xl text-xs font-bold shadow-sm cursor-pointer transition active:scale-95 shrink-0"',
'            title="Importar cobranças direto de planilhas copiando e colando"',
'          >',
'            <ClipboardList className="w-4.5 h-4.5" />',
'            <span>Importar</span>',
'          </button>',
'          ',
'          <button',
'            onClick={() => setIsNewCobrancaOpen(true)}',
'            className="flex items-center gap-2 px-4 py-2.5 bg-rose-600 hover:bg-rose-500 text-white rounded-xl text-xs font-bold shadow-md shadow-rose-900/10 cursor-pointer transition active:scale-95 shrink-0"',
'          >',
'            <Plus className="w-4 h-4" />',
'            <span>Inserir Manual</span>',
'          </button>',
'        </div>',
'      </div>');
fs.writeFileSync('src/components/CobrancasPage.tsx', lines.join('\n'), 'utf8');
