with open("server.ts", "r") as f:
    code = f.read()

replacement = """    N8N_COMPETITORS_WEBHOOK_URL: process.env.N8N_COMPETITORS_WEBHOOK_URL || "",
    N8N_TEST_COMPETITORS_WEBHOOK_URL: process.env.N8N_TEST_COMPETITORS_WEBHOOK_URL || "",
    USE_N8N_TEST_COMPETITORS: process.env.USE_N8N_TEST_COMPETITORS || "false",
    PAUSE_COMPETITORS_JOB: process.env.PAUSE_COMPETITORS_JOB || "false",

    N8N_ABSENCES_WEBHOOK_URL: process.env.N8N_ABSENCES_WEBHOOK_URL || "",
    N8N_TEST_ABSENCES_WEBHOOK_URL: process.env.N8N_TEST_ABSENCES_WEBHOOK_URL || "",
    USE_N8N_TEST_ABSENCES: process.env.USE_N8N_TEST_ABSENCES || "false",
    PAUSE_ABSENCES_JOB: process.env.PAUSE_ABSENCES_JOB || "false",

    N8N_ABSENCE_APPROVAL_WEBHOOK_URL: process.env.N8N_ABSENCE_APPROVAL_WEBHOOK_URL || "",
    N8N_TEST_ABSENCE_APPROVAL_WEBHOOK_URL: process.env.N8N_TEST_ABSENCE_APPROVAL_WEBHOOK_URL || "",
    USE_N8N_TEST_ABSENCE_APPROVAL: process.env.USE_N8N_TEST_ABSENCE_APPROVAL || "false",
    PAUSE_ABSENCE_APPROVAL_JOB: process.env.PAUSE_ABSENCE_APPROVAL_JOB || "false",

    PAUSE_ALL_N8N_WEBHOOKS: process.env.PAUSE_ALL_N8N_WEBHOOKS || "false\"\"\"
replacement = replacement[:-3] + '\"\"\"'

orig = """    N8N_COMPETITORS_WEBHOOK_URL: process.env.N8N_COMPETITORS_WEBHOOK_URL || "",
    N8N_TEST_COMPETITORS_WEBHOOK_URL: process.env.N8N_TEST_COMPETITORS_WEBHOOK_URL || "",
    USE_N8N_TEST_COMPETITORS: process.env.USE_N8N_TEST_COMPETITORS || "false",
    PAUSE_COMPETITORS_JOB: process.env.PAUSE_COMPETITORS_JOB || "false",

    PAUSE_ALL_N8N_WEBHOOKS: process.env.PAUSE_ALL_N8N_WEBHOOKS || "false\"\"\"
orig = orig[:-3] + '\"\"\"'

code = code.replace(orig, replacement)

code = code.replace(
    "const keys = ['USE_N8N_TEST_AGENDAMENTO', 'USE_N8N_TEST_NEW_TASK', 'USE_N8N_TEST_OVERDUE_TASKS', 'USE_N8N_TEST_LEAD_INACTIVITY', 'USE_N8N_TEST_UPGRADE_BASE', 'USE_N8N_TEST_POS_VENDA', 'USE_N8N_TEST_COBRANCAS', 'USE_N8N_TEST_VENDAS_SVA', 'USE_N8N_TEST_INDICACOES', 'USE_N8N_TEST_COMPETITORS'];",
    "const keys = ['USE_N8N_TEST_AGENDAMENTO', 'USE_N8N_TEST_NEW_TASK', 'USE_N8N_TEST_OVERDUE_TASKS', 'USE_N8N_TEST_LEAD_INACTIVITY', 'USE_N8N_TEST_UPGRADE_BASE', 'USE_N8N_TEST_POS_VENDA', 'USE_N8N_TEST_COBRANCAS', 'USE_N8N_TEST_VENDAS_SVA', 'USE_N8N_TEST_INDICACOES', 'USE_N8N_TEST_COMPETITORS', 'USE_N8N_TEST_ABSENCES', 'USE_N8N_TEST_ABSENCE_APPROVAL'];"
)

code = code.replace(
    "if (!key || !['USE_N8N_TEST_AGENDAMENTO', 'USE_N8N_TEST_NEW_TASK', 'USE_N8N_TEST_OVERDUE_TASKS', 'USE_N8N_TEST_LEAD_INACTIVITY', 'PAUSE_LEAD_INACTIVITY_JOB', 'USE_N8N_TEST_UPGRADE_BASE', 'PAUSE_ALL_N8N_WEBHOOKS', 'USE_N8N_TEST_POS_VENDA', 'PAUSE_AGENDAMENTO_JOB', 'PAUSE_NEW_TASK_JOB', 'PAUSE_OVERDUE_TASKS_JOB', 'PAUSE_UPGRADE_BASE_JOB', 'PAUSE_POS_VENDA_JOB', 'USE_N8N_TEST_COBRANCAS', 'PAUSE_COBRANCAS_JOB', 'USE_N8N_TEST_VENDAS_SVA', 'PAUSE_VENDAS_SVA_JOB', 'USE_N8N_TEST_INDICACOES', 'PAUSE_INDICACOES_JOB', 'USE_N8N_TEST_COMPETITORS', 'PAUSE_COMPETITORS_JOB'].includes(key)) {",
    "if (!key || !['USE_N8N_TEST_AGENDAMENTO', 'USE_N8N_TEST_NEW_TASK', 'USE_N8N_TEST_OVERDUE_TASKS', 'USE_N8N_TEST_LEAD_INACTIVITY', 'PAUSE_LEAD_INACTIVITY_JOB', 'USE_N8N_TEST_UPGRADE_BASE', 'PAUSE_ALL_N8N_WEBHOOKS', 'USE_N8N_TEST_POS_VENDA', 'PAUSE_AGENDAMENTO_JOB', 'PAUSE_NEW_TASK_JOB', 'PAUSE_OVERDUE_TASKS_JOB', 'PAUSE_UPGRADE_BASE_JOB', 'PAUSE_POS_VENDA_JOB', 'USE_N8N_TEST_COBRANCAS', 'PAUSE_COBRANCAS_JOB', 'USE_N8N_TEST_VENDAS_SVA', 'PAUSE_VENDAS_SVA_JOB', 'USE_N8N_TEST_INDICACOES', 'PAUSE_INDICACOES_JOB', 'USE_N8N_TEST_COMPETITORS', 'PAUSE_COMPETITORS_JOB', 'USE_N8N_TEST_ABSENCES', 'PAUSE_ABSENCES_JOB', 'USE_N8N_TEST_ABSENCE_APPROVAL', 'PAUSE_ABSENCE_APPROVAL_JOB'].includes(key)) {"
)

with open("server.ts", "w") as f:
    f.write(code)
